# @package _global_

domain: ???
ckpt: null
xpname: ???

model:
  _target_: contrib.glorys12.fdvarnet.Lit4DVarNetSteppedSolver
  persist_rw: false
  opt_fn:
    _target_: contrib.glorys12.unet.cosanneal_lr_adam_base
    _partial_: true
    lr: 1e-4
    T_max: ${trainer.max_epochs}
  rec_weight:
    _target_: ocean4dvarnet.utils.get_triang_time_wei
    patch_dims: ${datamodule.xrds_kw.train.patch_dims}
    crop: {time: 0, lat: 4, lon: 4}
  val_rec_weight:
    _target_: ocean4dvarnet.utils.get_triang_time_wei
    patch_dims: ${datamodule.xrds_kw.val.patch_dims}
    crop: {time: 0, lat: 4, lon: 4}
  solver:
    _target_: contrib.glorys12.fdvarnet.InitializableSolver
    n_step: 5
    n_detach: 2
    lr_grad: 1e3
    prior_cost:
      _target_: ocean4dvarnet.models.BilinAEPriorCost
      dim_in: ${datamodule.xrds_kw.train.patch_dims.time}
      dim_hidden: 64
      bilin_quad: false
      downsamp: null
    obs_cost:
      _target_: ocean4dvarnet.models.BaseObsCost
    grad_mod:
      _target_: ocean4dvarnet.models.ConvLstmGradModel
      dim_in: ${datamodule.xrds_kw.train.patch_dims.time}
      dim_hidden: 96
  norm_stats: ${datamodule.norm_stats}

defaults:
  - base
  - _self_
