# @package _global_

xpname: ttt

trainer:
  max_epochs: 350
  limit_train_batches: 250

datamodule:
  input_da:
    _target_: contrib.glorys12.load_glorys12_data_on_fly_inp
    tgt_path: /SCRATCH/d22zhu/glorys12_2010_2019_daily_sla_4th.nc
    tgt_var: sla
    inp_path: /SCRATCH/d22zhu/mask_6nadirs_4th.nc
    inp_var: inp
    val_path: /SCRATCH/d22zhu/validation-2021-0.25deg.nc
  xrds_kw:
    train:
      patch_dims: {time: 15, lat: 48, lon: 48}
      strides: {time: 1, lat: 40, lon: 40}
      domain_limits: ${domain.train}
      noise: .03
    val:
      patch_dims: {time: 15, lat: 48, lon: 48}
      strides: {time: 1, lat: 40, lon: 40}
      domain_limits: ${domain.train}
      noise: null
  dl_kw: {batch_size: 256, num_workers: 4}
  domains:
    val:
      time: {_target_: builtins.slice, _args_: ['2021-01-01', '2021-12-31']}
  norm_stats:  # norm values from tgt
    val:
    - 0.08624135039425909
    - 0.10271981565166008

model:
  opt_fn:
    lr: 3e-4
  solver:
    _target_: ocean4dvarnet.models.GradSolver
    n_step: 10
    prior_cost:
      downsamp: null

defaults:
  - glo12-sla
  - _self_
