method:
  # -------------------------------------------------------------------
  # SLA
  # -------------------------------------------------------------------
  name: fdvarUnet-no-lwe
  checkpoint: /Odyssey/private/d22zhu/Lab/4dvarnet-global-mapping/outputs/fdvarunet/unet_unrolling_5iter_grad/checkpoints/best.ckpt
  config: /Odyssey/private/d22zhu/Lab/4dvarnet-global-mapping/outputs/fdvarunet/.hydra/config.yaml

  input_data: data/global_sla_0.25_without_lwe.nc
  input_var: sla_filtered
  output_var: sla
  ensemble_size: 10
  ensemble_noise: .2

dims:
  patch: 15-648-1488
  stride: 1-200-200
  # patch: 15-256-256
  # stride: 1-196-154
  res: .25
