method:
  # -------------------------------------------------------------------
  # SLA
  # -------------------------------------------------------------------
  name: unet-default-best-noensemble
  # checkpoint: /Odyssey/private/d22zhu/Lab/4dvarnet-global-mapping/outputs/2025-11-04/unet-32lon-21139-17-17-52/ronan/checkpoints/best.ckpt
  # config: /Odyssey/private/d22zhu/Lab/4dvarnet-global-mapping/outputs/2025-11-04/unet-32lon-21139-17-17-52/.hydra/config.yaml
  checkpoint: /Odyssey/private/d22zhu/Lab/4dvarnet-global-mapping/outputs/2025-11-12/unet-valnolon-21928-17-32-14/ronan/checkpoints/last.ckpt
  config: /Odyssey/private/d22zhu/Lab/4dvarnet-global-mapping/outputs/2025-11-12/unet-valnolon-21928-17-32-14/.hydra/config.yaml

  input_data: data/global_sla_0.25.nc
  input_var: sla_filtered
  output_var: sla
  ensemble_size: 10
  ensemble_noise: .2

dims:
  patch: 15-648-1488
  stride: 1-200-200
  res: .25
